### ISSUE TITLE
github_stats.py: bug in fetch_github() exception handling code

### ISSUE THREAD

**Issue by solidgoldbomb** [myano/jenni#176]
I'm not sure exactly what triggered the error talking to github but once it happened, this line of code failed at runtime due to ```jenni``` not being a defined symbol in this context.

https://github.com/myano/jenni/blob/master/modules/github_stats.py#L38

```
Connecting to irc.freenode.net:6697... connected!
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python2.7/asyncore.py", line 468, in handle_write_event
    self.handle_write()
  File "/usr/lib/python2.7/asynchat.py", line 174, in handle_write
    self.initiate_send()
  File "/usr/lib/python2.7/asynchat.py", line 244, in initiate_send
    del self.producer_fifo[0]
IndexError: deque index out of range

Traceback (most recent call last):
  File "/home/stac/code/jenni/modules/github_stats.py", line 204, in gh_prs
    result = github_prs(jenni, origterm)
  File "/home/stac/code/jenni/modules/github_stats.py", line 75, in github_prs
    content = fetch_github(pr_url, project)
  File "/home/stac/code/jenni/modules/github_stats.py", line 38, in fetch_github
    jenni.say("An error occurred fetching information from Github: {0}".format(e))
NameError: global name 'jenni' is not defined
```

**Comment by kaneda** [comment]
@solidgoldbomb can you explain how you're starting jenni?

**Comment by myano** [comment]
I fixed the output of the error with a5b0198ee912f5a5f6953dc7a276af0c5515ba15

**Comment by solidgoldbomb** [comment]
@kaneda, I was running ```./jenni``` from the top of my git tree.

The fix from @myano addresses the issue I was pointing out.  ```jenni``` is now in scope in ```fetch_github()```.  Thanks.

**Comment by kaneda** [comment]
Thanks @myano

**Comment by myano** [comment]
@solidgoldbomb @kaneda you're welcome, :-)
